export function storiesTemplate(componentName: string) {
  return `
import React from 'react';
import {Meta, Story} from '@storybook/react/types-6-0';

import {${componentName}, ${componentName}Props} from './${componentName}';
// Learn how to write stories:
// https://master--6054e7fc826ed700218e4b3b.chromatic.com/?path=/story/documentation-how-to-write-stories--page
// To disable comments generated by the extension, search for …
export default {
  title: 'components/${componentName}',
  component: ${componentName},
  parameters: {
    // Embedding Figma designs
    // The embed appears in the "Design" tab of the story
    // Learn more: https://pocka.github.io/storybook-addon-designs/?path=/docs/docs-figma-readme--page
    design: {
      type: 'figma',
      url: 'https://www.figma.com/file/...?node-id=...',
    },
  },
} as Meta;

// 👇 We create a "template" of how args map to rendering
const Template: Story<${componentName}Props> = (args) => <${componentName} {...args} />;

// 👇 Each story then reuses that template
export const Basic = Template.bind({});

// Story args
// Learn more: https://storybook.js.org/docs/react/writing-stories/args
Basic.args = {};
`.trimLeft();
}
