export function storiesTemplate(
  componentName: string,
  verboseComments: boolean
) {
  let text =
    `import React from 'react';\n` +
    `import {Meta, StoryFn} from '@storybook/react';\n\n` +
    `import {${componentName}, Props} from './${componentName}';\n\n`;

  if (verboseComments) {
    text =
      text +
      `// Learn how to write stories:\n` +
      `// https://github.com/Shopify/web/blob/master/app/stories/02-HowToWriteStories.stories.mdx\n`;
    +`// To disable comments generated by the extension, search for 'verbose stories' in VS Code settings\n`;
  }

  text =
    text +
    `const meta: Meta = {\n` +
    `  title: 'components/${componentName}',\n` +
    `  component: ${componentName},\n` +
    `  parameters: {\n`;

  if (verboseComments) {
    text =
      text +
      `    // Embedding Figma designs\n` +
      `    // The embed appears in the "Design" tab of the story\n` +
      `    // Learn more: https://pocka.github.io/storybook-addon-designs/?path=/docs/docs-figma-readme--page\n`;
  }

  text =
    text +
    `    design: {\n` +
    `      type: 'figma',\n` +
    `      url: 'https://www.figma.com/file/...?node-id=...',\n` +
    `    },\n` +
    `  },\n` +
    `};\n\n` +
    `export default meta;\n\n`;
    
  if (verboseComments) {
    text = text + `// 👇 We create a "template" of how args map to rendering\n`;
  }
  
  text =
    text +
    `const Template: StoryFn<${componentName}Props> = (args) => <${componentName} {...args} />;\n\n`;

  if (verboseComments) {
    text = text + `// 👇 Each story then reuses that template\n`;
  }

  text = text + `export const Basic = Template.bind({});\n\n`;

  if (verboseComments) {
    text =
      text +
      `// Story args\n` +
      `// Learn more: https://storybook.js.org/docs/react/writing-stories/args\n`;
  }

  text = text + `Basic.args = {\n` +
    ` exampleBool: true,\n` +
    ` exampleSelect: 'option1',\n` +
    `};\n\n` +

    `Basic.argTypes = {\n` +
    ` exampleSelect: {\n` +
    `   control: {\n` +
    `     type: 'select',\n` +
    `     options: ['option1', 'option2'],\n` +
    `   },\n` +
    ` },\n` +
    `};\n\n`;

  return text;
}
