export function storiesTemplate(
  componentName: string,
  verboseComments: boolean,
  importReact: boolean
) {
  let text =
    (importReact ? "import React from 'react';\n" : '') +
    `import type {Meta, StoryObj} from '@storybook/react';\n\n` +
    `import type {${componentName}Props} from './${componentName}';\n` +
    `import {${componentName}} from './${componentName}';\n\n`;

  if (verboseComments) {
    text =
      text +
      `// Learn how to write stories:\n` +
      `// https://web.docs.shopify.io/docs/guides/storybook/how-to-write-story-files\n`;
    +`// To disable comments generated by the extension, search for 'verbose stories' in VS Code settings\n\n`;

    text = text +
        `// To learn how to migrate existing stories to Storybook 7+ and the new CSF format:\n`
        + `// https://github.com/storybookjs/storybook/blob/next/MIGRATION.md\n`;
  }

  text =
    text +
    `const meta: Meta<typeof ${componentName}> = {\n` +
    `  component: ${componentName},\n` +
    `  parameters: {\n`;

  if (verboseComments) {
    text =
      text +
      `    // Embedding Figma designs\n` +
      `    // The embed appears in the "Design" tab of the story\n` +
      `    // Learn more: https://pocka.github.io/storybook-addon-designs/?path=/docs/docs-figma-readme--page\n`;
  }

  text =
    text +
    `    design: {\n` +
    `      type: 'figma',\n` +
    `      url: 'https://www.figma.com/file/...?node-id=...',\n` +
    `    },\n` +
    `  },\n` +
    `};\n\n` +
    `export default meta;\n\n`;


  text =
    text +
    `type Story = StoryObj<typeof ${componentName}>;\n\n`;


  if (verboseComments) {
    `// Story args\n` +
    `// Learn more: https://storybook.js.org/docs/react/writing-stories/args\n`;
  }

  if (verboseComments) {
    text = text + `// 👇 We create a "template" of how args map to rendering\n`;
  }
  text = text + `export const Basic: Story = { args: {} };\n\n`;

  return text;
}
